name: Check Testcase JSON schema on PRs
on:
    pull_request:
        paths:
            - 'tests/**/*.json'

permissions:
  contents: read
  pull-requests: write

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v5
      - name: json-yaml-validate
        id: json-yaml-validate
        uses: GrantBirki/json-yaml-validate@v4.0.0
        with:
          comment: "true"
          json_schema: schema.json
          base_dir: "./tests/"
